name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thanks for creating the issue **#**, our team will look in to it right away!"
        pr-message: "Thanks for the PR **#** ! Our team will verify and merge it as soon as possible ✌"
